### ISSUE TITLE
License

### ISSUE THREAD

**Issue by scheiblr** [dothinking/pdf2docx#1]
Hi, 

first I'd like to thank you for opening this code.

Unfortunately, you may not be aware of this, legally, without a license, no one can use your code, which btw. makes any contribution legally impossible (http://opensource.stackexchange.com/q/1720/775).

As we think about to further develop to this project, but at the current state would just not be allowed to do it. It would be nice if you could add a License to your project.

Cheers

**Comment by scheiblr** [comment]
As we analyzed your code, we saw, that the project indispensable bases on AGPL-licensed code. Therefore, you have to License your code on AGPL as well.

**Comment by dothinking** [comment]
Hi @scheiblr,

Many thanks for your kind and helpful suggestions. `GPL v3` is added according to the dependency `PyMuPDF`.

I got problems to improve the conversion quality, e.g. table format, word wrap, so no updates for months. Welcome to contribute and improve this project.
