### ISSUE TITLE
中文技术文档连接404

### ISSUE THREAD

**Issue by retsyo** [dothinking/pdf2docx#101]
主页说的这个
https://dothinking.github.io/pdf2docx/techdoc.html
已经404了

**Comment by dothinking** [comment]
最新版文档还没发布，主页提前占了个坑 😄 ，技术文档源码看这儿


https://github.com/dothinking/pdf2docx/blob/master/doc/techdoc.rst

**Comment by retsyo** [comment]
赞
也许学习之后，能做出一个电子发票提取软件。好吧，这只是我的一个flag；我立的flag很多，也不在乎多立一个

**Comment by dothinking** [comment]
非扫描版的且格式固定的发票还是可以的 😸
