### ISSUE TITLE
problem with arabic letters 

### ISSUE THREAD

**Issue by MesterPerfect** [dothinking/pdf2docx#106]
hi
I have a problem with your library with Arabic letters
This library converts characters very well
But the resulting text is from left to right
While Arabic words are read from right to left
The resulting text will look like this 

```
،باتك ثيدحلا قدصأ َّنإف  ٍدمحم يده يدهلا ريخو-ملسو هلآو هيلع  ىلص- لكو ،اهتاثدحُم روملأا رشو ،
```

While the correct text should be like this 

```
، وشر األمور مُحدثاتها، وكل -صلى عليه وآله وسلم-وخير الهدي هدي محمدٍ فإنَّ أصدق الحديث كتاب،
```

This can be easily modified 

```
text = "،باتك ثيدحلا قدصأ َّنإف  ٍدمحم يده يدهلا ريخو-ملسو هلآو هيلع  ىلص- لكو ،اهتاثدحُم روملأا رشو ،"
print(text[-1])
"، وشر األمور مُحدثاتها، وكل -صلى عليه وآله وسلم-وخير الهدي هدي محمدٍ فإنَّ أصدق الحديث كتاب،"
```

But the problem is that the syntax is also reversed
And the correct text should be like this 

```
"فإنَّ أصدق الحديث كتاب، وخير  الهدي هدي محمدٍ صلى عليه وآله وسلم- ، وشر األمور مُحدثاتها، وكل"
```

I know it sounds a bit confusing, but I can explain more if you want to

**Comment by dothinking** [comment]
Sorry for the late reply.

It's not the first time I received issues on Arabic letters, but I didn't make it without any background on Arabic. My only understanding is the reading direction, as you illustrated, so it'd be great if you could share more on the syntax issue.

Including the correct words, the setting in MS word, e.g. reading direction, alignment mode, would be the next step.
