### ISSUE TITLE
有表格的情况下PDF转docx会出现空白页问题

### ISSUE THREAD

**Issue by lidh15** [dothinking/pdf2docx#107]
我改了一下表格里的内容以后再转文档，表格的面积就变得非常大，出现了空白页

**Comment by dothinking** [comment]
不知方便提供你的pdf文件？可以删除敏感信息，仅保留足以复现问题的部分即可，谢谢

**Comment by lidh15** [comment]
> 不知方便提供你的pdf文件？可以删除敏感信息，仅保留足以复现问题的部分即可，谢谢

链接: https://pan.baidu.com/s/1r8KIC5ODDNBO0QrAI5KbZg 提取码: pry4
执行python脚本处理pdf文件后得到的docx文件的第三页第四页可以看到空白表格

**Comment by lidh15** [comment]
有效期是一周，请您尽快下载

**Comment by dothinking** [comment]
主要原因是表格边界参差不齐（见下图），程序在合并单元格时出现问题造成表格解析失败，错误的表格布局引起跨页。

针对表格解析进行了改进，目前可以正常转换你提供的表格样式，近期将随`v0.5.3`版本一起发布。

![image](https://user-images.githubusercontent.com/13885442/154105833-e61b8df1-b292-4a01-94b3-860cc6f7d719.png)

**Comment by lidh15** [comment]
好的，期待试用新版本

**Comment by dothinking** [comment]
`v0.5.3`已发布，关闭问题。
