### ISSUE TITLE
支持文件流输入输出么？

### ISSUE THREAD

**Issue by verydemo** [dothinking/pdf2docx#108]
```
doc = fitz.open(stream=stream, filetype='pdf')
cv._fitz_doc = doc
cv.convert(docx_file)
cv.close()
```
输入我找到解决办法，输入文件流。 输出应该怎么弄？

**Comment by dothinking** [comment]
好问题，你把上面的`docx_file`换成一个流对象，最后的docx就可以写入这个流了。

你的输入流采用了变通的方式，下一版本我把它直接加入构造函数中去。

**Comment by verydemo** [comment]
你好！ 你的代码不支持流对象。 
```
![image](https://user-images.githubusercontent.com/29354679/129222869-9dc02ac3-519f-4c6f-a3ec-a6ebc3eff8ae.png)

```
os.path.exists() 不支持流对象。

**Comment by dothinking** [comment]
啊，是的。那你将就改一下源码，把框出来的那一行放到`if`判断里去：

```python
if isinstance(filename, str):
    ...
```

**Comment by dothinking** [comment]
已在新发布的`v0.5.7`中支持，参考用法： https://github.com/ArtifexSoftware/pdf2docx/issues/223#issuecomment-1879051886
