### ISSUE TITLE
你好，关于转换后图片颠倒的问题

### ISSUE THREAD

**Issue by yuxiao1125** [dothinking/pdf2docx#110]
图片旋转了90°，
pdf如下
[111.pdf](https://github.com/dothinking/pdf2docx/files/6980170/111.pdf)

**Comment by dothinking** [comment]
感谢提出问题和测试文件。

## 原因分析：

- 原始图片确实是以旋转了90度的样子存在于PDF文件中的，参考下图所示图片原始信息，其中宽度大于高度，表明图片确实是“横”着的。

- 但为何显示的是正确的图片？因为PDF的渲染机制允许页面旋转一定角度后显示，虽然绝大多数PDF都没有旋转，但本例旋转了90度，而目前程序没有正确处理这种情况。

![image](https://user-images.githubusercontent.com/13885442/153642199-0a8d03b9-6aa4-4f0b-bf8b-f44415205dc9.png)


## 解决思路

检测页面旋转角度，如果不为0，则对图片旋转相应的角度。

目前已在开发分支中修复，近期会发布新版本。

**Comment by dothinking** [comment]
`0.5.3`已发布，关闭此问题。
