### ISSUE TITLE
A bug in Shape.py

### ISSUE THREAD

**Issue by AAAves** [dothinking/pdf2docx#111]
在shape.Shape.py: 75行的这个函数
```python
@type.setter
def type(self, rect_type:RectType): 
    self._type = rect_type.value`
```

当text.TextSpan.py: 313行
```python
else:
     rect.type = rect.default_type
```
这里的default_type是一个int型，因此调用上面shape中的函数会出现类型错误

我把Shape.py改成这样以后不报错了:
```python
   @type.setter
    def type(self, rect_type:RectType):
        if isinstance(rect_type,int):
            self._type = rect_type
        elif isinstance(rect_type,RectType):
            self._type = rect_type.value
```

会出现bug的pdf：https://openaccess.thecvf.com/content_ICCV_2019/papers/Liu_Coherent_Semantic_Attention_for_Image_Inpainting_ICCV_2019_paper.pdf

**Comment by dothinking** [comment]
感谢指出bug、提供测试文件及解决方法。这确实是`v0.5.2`版出现概率非常高的一个问题，你的修改通过类型判断可以解决问题。

经检查，我也已经在开发分支中修复了这个问题：首先直接删除了出错的`else`分支，然后把接下来的317行从

```python
# check rect type again
if rect.type==rect.default_type: return False
```

改为：

```python
# check rect type again
if not rect.is_determined: return False
```

抱歉这么晚才回复。
