### ISSUE TITLE
a bug in Layout.py

### ISSUE THREAD

**Issue by sundaolin9527** [dothinking/pdf2docx#115]
![image](https://user-images.githubusercontent.com/51184975/134891246-ee74d8da-e3f1-4325-be68-e3963c7b615a.png)

**Comment by sundaolin9527** [comment]
请问下block.parse(**settings)调用的是哪个类的parse方法啊，ps: Block类没有parse方法啊

**Comment by sundaolin9527** [comment]
使用的测试pdf文件就是自带的demo.pdf

**Comment by qunosen** [comment]
我也遇到了这个问题, 你解决了吗？

**Comment by qunosen** [comment]
我也遇到了这个问题, 你解决了吗？@sundaolin9527

**Comment by sundaolin9527** [comment]
> 我也遇到了这个问题, 你解决了吗？@sundaolin9527

没有

**Comment by dothinking** [comment]
> 1. 请问下block.parse(**settings)调用的是哪个类的parse方法啊，ps: Block类没有parse方法啊

参考`filter`函数中根据 `is_table_block` 作了筛选，也就是 `pdf2docx.table.TableBlock` 类的 `parse` 方法

> 2.使用的测试pdf文件就是自带的demo.pdf，在解析第4页时会出现错误maxmum recursion depth exceeded

`v0.5.2`版本未能复现你的问题，请问你的版本？

---
抱歉拖了这么久才处理。
