### ISSUE TITLE
#95 reopen : [ERROR] corrupt cmap table format 4 (data length: 146, header length: 152)

### ISSUE THREAD

**Issue by Manuel248** [dothinking/pdf2docx#117]
Hi i have the same problem as "BinhLTTB". 
When converting a pdf i get the error above , other files work well. 
The pdf-file is attached below.

[manyreqs- no table - 2004 - rlcs.pdf](https://github.com/dothinking/pdf2docx/files/7278146/manyreqs-.no.table.-.2004.-.rlcs.pdf)

**Comment by swoneeye** [comment]
我也出现了这种情况  也发现了报错的pdf   用adobe 可以转换  用wps 也能正常打开

**Comment by swoneeye** [comment]
当我将抛出异常的代码assert  注释掉之后, 它就可以正常的进行后续处理了, 并不会报任何错误. 完成后的docx 目前看起来也没有异常.

fontTools/ttLib/tables/_c_m_a_p.py 的第249行的assert
往往 header length 大于 data length  不知道返回来会不会有异常情况

**Comment by swoneeye** [comment]
当我将抛出异常的代码assert 注释掉之后, 它就可以正常的进行后续处理了, 并不会报任何错误. 完成后的docx 目前看起来也没有异常.

fontTools/ttLib/tables/_c_m_a_p.py 的第249行的assert

但是!  我又换了一个文件,  他会卡在getLinks 或 getDrawings 中的某个 上面  直至memory error  程序退出, 
也就是说肯定还是有问题的,  注释assert 并不是一个很好的办法,   这可能是pdf 文件的问题,  
我发现了一种情况, 当文字版pdf 中插入了扫描版的页面, 或者他们是混合的,它会出现这个情况.  很遗憾不能提供这个pdf
因此 , 正经的PDF是没啥问题的 而且很快,  不正经的PDF 处处是问题-.-

**Comment by dothinking** [comment]
@Manuel248 Thanks for providing the test file. Now the font processing is simplified, so this issue should be fixed. 

The new version of pypi installation has not been published yet, but you could try it in advance per git online installation

```
$ pip install git+git://github.com/dothinking/pdf2docx.git@dev --upgrade
```

**Comment by dothinking** [comment]
v0.5.3版已发布。
