### ISSUE TITLE
Error on Amazon Linux 2 (3.7) platform - Critical

### ISSUE THREAD

**Issue by vatsal2210** [dothinking/pdf2docx#118]
I am running an application using Flask and parsing the document using pdf2docx. 

I am having an issue with tkinter as Amazon Linux 2 platform doesn't support GUI. 

What are the options, and how can I resolve this error?

```
from pdf2docx import parse
File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/pdf2docx/__init__.py", line 3, in <module>
from .main import parse
File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/pdf2docx/main.py", line 6, in <module>
from .gui.App import App
File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/pdf2docx/gui/App.py", line 5, in <module>
from tkinter import Tk, messagebox
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by mateusmb** [comment]
Hello.

I've made a fork of this lib and removed everything related to tkinter and GUI functionality.
I've also uploaded it to Pypi with the name pdf2docxnogui. You can install it with pip or add in requirements.txt for your CI/CD pipeline. For the record, I'm currently actively using it in a service deployed to AWS with no problems.

@dothinking I kept all mentions to your repo/project. Let me know if you want to change anything to my fork. Here is the link: https://github.com/mateusmb/pdf2docxnogui

**Comment by dothinking** [comment]
@vatsal2210, understand your case. Definitely, this issue will be fixed, but it takes time to release a new version with other accumulated updates. So, mateusmb's solution solves your problem perfectly.


@mateusmb, great, thanks for your work and comment.

**Comment by dothinking** [comment]
@vatsal2210, understand your case. Definitely, this issue will be fixed, but it takes time to release a new version with other accumulated updates. So, mateusmb's solution solves your problem perfectly.


@mateusmb, great, thanks for your work and comment.

**Comment by vatsal2210** [comment]
Did you publish your package @mateusmb? 

@dothinking It would be great help to fix those two minor fixes in your PR related to GUI. :)

**Comment by mateusmb** [comment]
> Did you publish your package @mateusmb? 
> 
> @dothinking It would be great help to fix those two minor fixes in your PR related to GUI. :) 

Yes, it's on Pypi https://pypi.org/project/pdf2docxnogui/0.1/

You can install it with pip install pdf2docxnogui

**Comment by dothinking** [comment]
`v0.5.3` is released, with this issue resolved.

**Comment by dothinking** [comment]
`v0.5.3` is released, with this issue resolved.
