### ISSUE TITLE
'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by a1046097466** [dothinking/pdf2docx#120]
'int' object has no attribute 'value'   转PDF为word时候，报这个错误

**Comment by foobacca** [comment]
I fixed this issue occurring by installing PyMuPDF==1.18.19.  If you use PyMuPDF>=1.19.0 I see the above error quite often (along with other errors about using method names that are no longer supported - basically changing camelCase method names to snake_case).

**Comment by dothinking** [comment]
> 'int' object has no attribute 'value' 转PDF为word时候，报这个错误

从错误信息上看，很可能是#111的问题，供参考。近期会发布一个修复版本。

**Comment by dothinking** [comment]
@foobacca, thanks for the reminder. I'll check these issues and try to align with PyMuPDF 1.19.x for the coming new version.

**Comment by dothinking** [comment]
@foobacca, thanks for the reminder. I'll check these issues and try to align with PyMuPDF 1.19.x for the coming new version.
