### ISSUE TITLE
_tkinter error: It not possible import module tkinter

### ISSUE THREAD

**Issue by enzococca** [dothinking/pdf2docx#121]
Hi 
I integrated your system into my plugin and untill version 0.4.6 It worked very well.
When you put inside your system the gui made by tkinter I can't upgrade pdf2docx. So if possible to insert  a try /except in the file main.py when you import the gui?

thanks
E

**Comment by dothinking** [comment]
Thank you for the reporting.  Fix is planned, hopefully the end of this month.

Linked to #118.

**Comment by dothinking** [comment]
`v0.5.3` is released.

**Comment by enzococca** [comment]
Thanks a lot. This is magic
