### ISSUE TITLE
pdf转docx 转换结果空白

### ISSUE THREAD

**Issue by bikerr** [dothinking/pdf2docx#123]
PDF下载地址
[3B01722322037348.pdf](https://github.com/dothinking/pdf2docx/files/7749397/3B01722322037348.pdf)

**Comment by dothinking** [comment]
感谢提供很好的一个例子。经测试，确实是当前版本的一个bug。

## 原因分析

这个文件表面上看起来一页就是一张图片，实际上是由多张图片重叠而成的，参见下图。截至`0.5.2`版本，对这种多图重叠的情况存在处理逻辑上的错误，导致所有图片都没有显示。

![image](https://user-images.githubusercontent.com/13885442/153714739-f238911b-72e0-4993-9e0c-6496e6a6a0b5.png)


## 解决思路

完美的方案是分别提取各张图片，然后依样重叠到Word文档中，但是“重叠”涉及到图片透明度的问题。具体到这个文件，重叠图片中的一张是主图，其余图片只有alpha通道（透明度），但目前从PDF文件提取仅有alpha通道的图片还存在一些技术难度。因此，当前实施的是退而求其次的方案：

计算原始重叠图片的叠加区域，然后直接截图得到最终一张图的效果。

**Comment by dothinking** [comment]
目前已在开发分支中实现，近期将在`0.5.3`版本中发布。

**Comment by dothinking** [comment]
新版本已发布，暂时关闭问题。如果问题，欢迎测试留言。
