### ISSUE TITLE
Rotate the image 90°

### ISSUE THREAD

**Issue by oldlwhite** [dothinking/pdf2docx#125]
This is the source file
[test.pdf](https://github.com/dothinking/pdf2docx/files/7852137/test.pdf)

**Comment by dothinking** [comment]
Thanks for providing the test document. 

Same issue with #110, the root cause is page rotation. It was fixed and plans to be released in the coming v0.5.3.

**Comment by dothinking** [comment]
close issue for now since `v0.5.3` is released.
