### ISSUE TITLE
ImportError: cannot import name 'Parse' from partially initialized module 'pdf2docx' (most likely due to a circular import) (c:\Users\amite\Desktop\pdf2docx\pdf2docx.py)

### ISSUE THREAD

**Issue by Amiteshvijay** [dothinking/pdf2docx#127]
![image](https://user-images.githubusercontent.com/90886199/152650158-dbccf228-a6c9-44c0-8db6-57d7664ca966.png)

**Comment by dothinking** [comment]
Change your file `pdf2docx.py` to another name, e.g., `pdf2word.py`, which should be different from the library name `pdf2docx`.

**Comment by Amiteshvijay** [comment]
it' work. thank you
