### ISSUE TITLE
Replace font "AbriBar128s" with "Times New Roman" due to lack of data.

### ISSUE THREAD

**Issue by Yuwenqing** [dothinking/pdf2docx#131]
When I tried to convert pdf file with barcode I got below error: "Replace font "AbriBar128s" with "Times New Roman" due to lack of data." How can I solve this problem.
Thanks

**Comment by dothinking** [comment]
This is just a warning message. What's the issue on your docx file? It's great if you could upload the pdf file for testing.

**Comment by Yuwenqing** [comment]
Thank for reply. Please see the attachment.












余文清


***@***.***


13918188758







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: dothinking  ***@***.***>
 

 
 发送时间: 2022-02-17 21:57:57
 

 
 收件人:dothinking/pdf2docx ***@***.***> 

 
 抄送:余文清 ***@***.***>,Author ***@***.***> 

 
 主题: Re: [dothinking/pdf2docx] Replace font "AbriBar128s" with "Times NewRoman" due to lack of data. (Issue #131)
 





 This is just a warning message. What's the issue on your docx file? It's great if you could upload the pdf file for testing.

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yuwenqing** [comment]
Upload the file in mail.

**Comment by Yuwenqing** [comment]
已在Github里直接提交了。













余文清


***@***.***


13918188758







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: dothinking  ***@***.***>
 

 
 发送时间: 2022-02-18 13:47:47
 

 
 收件人:dothinking/pdf2docx ***@***.***> 

 
 抄送:余文清 ***@***.***>,Author ***@***.***> 

 
 主题: Re: [dothinking/pdf2docx] Replace font "AbriBar128s" with "Times NewRoman" due to lack of data. (Issue #131)
 





 Upload the file in mail.

 邮箱中没看到附件，麻烦重新发送一遍。

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dothinking** [comment]
收到，看了一下，应该是你电脑上没有安装`AbriBar128s`这种二维码字体，导致二维码以文本形式显示在Word中了。可以尝试下载安装这种字体。

而PDF文件在被创建时自动内置了文本显示所需的字体，所以即便目标系统上没有该字体也可以正常显示。这也是PDF能够跨设备的原因之一。

**Comment by Yuwenqing** [comment]
已安装该字体，能在Word里选到该字体，但是还是不行。

**Comment by Yuwenqing** [comment]
字体安装后需要重新安装pdf2docx可以解决该问题。

**Comment by dothinking** [comment]
发现一个小问题，我在网上下载的一个`abribar128s.ttf`字体似乎不能正确显示数字`0`，例如`1230`在该字体下，最后一位的`0`被错误显示为竖写的`ABRI`了。

![image](https://user-images.githubusercontent.com/13885442/154909775-96881e50-fe91-4904-b359-c8f32856d439.png)

**Comment by Yuwenqing** [comment]
这个问题我也遇到了。暂时没有找到解决办法。
