### ISSUE TITLE
请问列车运行图这样的文件可否转换

### ISSUE THREAD

**Issue by kuaidianbiye1994** [dothinking/pdf2docx#135]
[01_Bangkok 1 Diagram_改.pdf](https://github.com/dothinking/pdf2docx/files/8655407/01_Bangkok.1.Diagram_.pdf)
[01_Bangkok 1 Diagram.pdf](https://github.com/dothinking/pdf2docx/files/8655411/01_Bangkok.1.Diagram.pdf)
首先感谢大佬的库，是我毕设的最后希望了。。
如题，我想转换上传的列车运行图这样的文件。列车运行图就只包含一些文本和一张大矢量图，其中文本都为文字格式，不是图片格式。
一开始我想直接编辑pdf格式的内容，我的计划是将其中泰语部分翻译成汉语再输出一个新运行图，但是利用python在pdf中直接修改难以实现，故想到转换成docx曲线救国。。

**Comment by dothinking** [comment]
我试了一下，抱歉这个库目前对你的文件的转换效果很差。

不知道你的具体需求是什么，把文件翻译成中文？根据你的描述，文件格式相对固定，我反而觉得直接用python修改pdf比较可行，可以尝试一下`PyMuPDF`这个库。

**Comment by kuaidianbiye1994** [comment]
是这样的，我毕设想做一个中泰德三国列车运行图互译的小程序。。
所以输入的东西很固定就是这样的列车运行图，输出的是另一种语言的列车运行图。
具体功能就是把这个运行图中的文字翻译并替换成目标语言，再输出一张新pdf的图（实在不行png或是jpg格式输出也行）。其中，中德互译相对复杂点，需要把pdf旋转90°后再翻译替换，其中文本需要变成从上往下竖直方向的了（我想这会增加不少难度吧。。）
基于此，我一开始的思路是想直截了当编辑pdf中的文本，但是很难做到一个精准定位并编辑（我一开始真的寻思这不难啊，都不用对图做修改，就改改文本罢了），故就想到了转docx，因为docx中的文本相对好编辑。
再次感谢大佬的帮助，我是铁路专业的，用python完全是出于毕设的要求，但是现在被搞得有点焦头烂额了。。。

**Comment by kuaidianbiye1994** [comment]
> 我试了一下，抱歉这个库目前对你的文件的转换效果很差。
> 
> 不知道你的具体需求是什么，把文件翻译成中文？根据你的描述，文件格式相对固定，我反而觉得直接用python修改pdf比较可行，可以尝试一下`PyMuPDF`这个库。

是这样的，我毕设想做一个中泰德三国列车运行图互译的小程序。。
所以输入的东西很固定就是这样的列车运行图，输出的是另一种语言的列车运行图。
具体功能就是把这个运行图中的文字翻译并替换成目标语言，再输出一张新pdf的图（实在不行png或是jpg格式输出也行）。其中，中德互译相对复杂点，需要把pdf旋转90°后再翻译替换，其中文本需要变成从上往下竖直方向的了（我想这会增加不少难度吧。。）
基于此，我一开始的思路是想直截了当编辑pdf中的文本，但是很难做到一个精准定位并编辑（我一开始真的寻思这不难啊，都不用对图做修改，就改改文本罢了），故就想到了转docx，因为docx中的文本相对好编辑。
再次感谢大佬的帮助，我是铁路专业的，用python完全是出于毕设的要求，但是现在被搞得有点焦头烂额了。。。

**Comment by dothinking** [comment]
`PyMuPDF`是一个开源免费的支持PDF信息提取和修改的Python库，根据你的描述，我大致尝试了一下：

1. 提取文本及其位置坐标
2. 翻译文本 -> 暂时简化为替换为字符A
3. 替换原来文本

先安装库：

```
pip install PyMuPDF
```

然后在控制台执行如下代码：`python code.py`

```python
# filename: code.py
import fitz

# 定义一个替换函数：把文本块`span`替换为指定文本`text`
def replace_span(page, span, text):
    page.draw_rect(span['bbox'], color=(1,0,0)) # 可以删除，画个框示意一下原来的位置
    page.add_redact_annot(span['bbox'], 
        text, 
        fontsize=span['size'], 
        fill=False, 
        text_color=fitz.sRGB_to_pdf(span['color']))

# 以你提供的第二个文件的第一页为例
doc = fitz.open('01_Bangkok.1.Diagram.pdf')
page = doc[0]

# 获取页面文本元素，数据格式参考：
# https://pymupdf.readthedocs.io/en/latest/textpage.html#structure-of-dictionary-outputs
raw = doc[0].get_text('dict')
spans = []
for block in raw['blocks']:
    if block['type']!=0: continue
    for line in block['lines']:
        spans.extend(line['spans'])

# 假设仅仅翻译坐标轴和标题数据，经观察恰好颜色都是黑色
for span in spans:
    if span['color']!=0: continue # 忽略黑色以外的所有彩色文字
    replace_span(span, 'A'*len(span['text'])) # 替换为A，这里假设和之前等长，实际翻译后可能字数不同

# 确认替换
doc[0].apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)

# 另存为新文件
doc.save("new.pdf", garbage=3, deflate=True)
```

局限：

- 运行图主区域倾斜文字的处理，以上代码通过颜色忽略之
- 泰文在清除原文字过程中可能有局部笔画的残留（具体参考下面演示结果）

**Comment by dothinking** [comment]
[new.pdf](https://github.com/dothinking/pdf2docx/files/8660837/new.pdf)

![image](https://user-images.githubusercontent.com/13885442/167612445-dad29805-45cb-46d7-80ae-f38f33bdf64f.png)

**Comment by dothinking** [comment]
> 图中的彩色文本是固定的，就是中泰德三语的“空载”、“满载”、“客运”、“货运”以及车次，完全可以借由颜色判断的思路去替代

绘图区域除了数字就是英文，这个也需要翻译吗？需要的话，麻烦地方在处理倾斜排列的文字。

> 所以我想到以语种来判断，即检测其中是否是泰语（或中文，德语），然后再操作

这是一个可行的思路，我可以尝试一下和之前写的示例代码合并。

> 但是我将其替换进以颜色判断的部分后报错了。。。。

我写的示例代码是基于`PyMuPDF`这个库的，不适用于`pdfplumber`。

> 如何逐步提取文本，逐步翻译，逐步替换。。这个真的很头疼，语言检测功能和翻译功能都不支持一次性大量文本输出

`pdfplumber`的`extract_text() `函数一次性提取文本，并没有分行分段等信息，所以你很难根据需要短句翻译。此外，它只是一个 **读** PDF信息的库，即便你做到断句和翻译了，怎么 **修改** 回原来的PDF？

**Comment by dothinking** [comment]
根据你的信息补充，我改进了一下代码，基于以下前提：

- 不处理绘图区域中的倾斜文本
- 不翻译目标语言（泰语，中文，德语）之外的文本，例如标题中的纯英文，数字等

进一步观察发现，示例文件中待翻译文本行由斜杠分隔的两部分组成： `泰语 / 英语`，例如 `ชุมทางบางซื่อ/ Bang Sue Junctio`，因此基本思路为：

- 忽略不满足此格式的文本
- 然后仅仅翻译前半部分到目标语言，例如 `ชุมทางบางซื่อ/ Bang Sue Junctio`的 `ชุมทางบางซื่อ`翻译为`邦苏交界处`
- 最后拼接回原来格式的文本： `邦苏交界处/ Bang Sue Junctio`

**为什么拆分后翻译？** 试验发现，直接混合语种文本的翻译质量比较差。

**Comment by dothinking** [comment]
```python
# filename: code.py
import re
import fitz
from googletrans import Translator


# 定义一个替换函数：把文本块`span`替换为指定文本`text`
def replace_span(page, span, text, font_name):
    page.draw_rect(span['bbox'], color=(1,0,0)) # 可以删除，画个框示意一下原来的位置
    page.add_redact_annot(span['bbox'], 
        text, 
        fontsize=span['size'], 
        fill=False, 
        fontname=font_name,
        text_color=fitz.sRGB_to_pdf(span['color']))


# 按预定义格式提取文本及位置
def collect_span(page):
    # 待翻译文本的三种格式
    rules = [
        re.compile(r'(.*?)[(](.*?)[)]'),
        re.compile(r'(.*?)/(.*?)-(.*?)/(.*?)$'), # 此规则需在前
        re.compile(r'(.*?)/(.*?)$')        
    ]

    # 获取页面文本元素，数据格式参考：
    # https://pymupdf.readthedocs.io/en/latest/textpage.html#structure-of-dictionary-outputs
    raw = page.get_text('dict')
    spans = []
    for block in raw['blocks']:
        if block['type']!=0: continue
        for line in block['lines']:
            # 忽略倾斜文本
            x, y = line['dir']
            if x*y!=0: continue
            
            for span in line['spans']:
                # 先初步过滤掉数字及纯大写字母
                text = span['text'].strip()
                if text.isdigit() or text.isupper(): 
                    continue

                # 按采集格式提取
                for rule in rules:                    
                    res = rule.findall(text)
                    if not res: continue
                    span['sources'] = res[0][0::2] # 待翻译部分，可能有多个
                    span['ens'] = res[0][1::2]      # 对应位置的英文对照
                    spans.append(span)
                    break
    return spans


# 翻译函数
def translate_span(translator, span, to_lang):
    text, sources, ens = span['text'], span['sources'], span['ens']
    for source, en in zip(sources, ens):        
        translated_text = translator.translate(en, dest=to_lang).text
        print(source, en, translated_text)
        text = text.replace(source.strip(), translated_text)
    return text

# 引入中文字体
def set_chinese_font(doc, font_name, font_file):
    doc[0].insert_text((0,0), " ", fontname=font_name, fontfile=font_file, render_mode=3)


if __name__=='__main__':
    
    # 以你提供的第一个文件为例
    doc = fitz.open('01_Bangkok.1.Diagram.pdf')

    # 以翻译成中文为例
    to_lang = 'zh-cn'
    translator = Translator()

    # 避免中文乱码，设置支持中文的字体，例如雅黑
    # 同理，翻译泰文需要事先提供支持泰文的字体
    font_name = None
    if to_lang=='zh-cn':
        font_name = 'yahei'
        set_chinese_font(doc, font_name, 'msyh.ttf') # 注意字体的绝对路径
    
    # 逐页提取和翻译
    for page in doc:
        spans = collect_span(page)        
        for span in spans:
            text = translate_span(translator, span, to_lang)
            print(f'translated {span["text"]} to {text}...')
            replace_span(page, span, text, font_name)

        # 确认替换
        page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)

    # 另存为新文件
    doc.save("new.pdf", garbage=3, deflate=True)
```

**Comment by dothinking** [comment]
以上代码结果：

![图片](https://user-images.githubusercontent.com/13885442/167788706-d9c9f096-2b0b-4a2c-b89c-84e9927ee5f6.png)

原来的翻译库达到翻译次数上限了，所以我换了另一个翻译库`googletrans`。翻译速度和效果都还不错，但个别地名翻译还是存在问题，交给你自己优化了。

![图片](https://user-images.githubusercontent.com/13885442/167789006-4fdba02a-bc49-4b78-b77e-aea1d4af95cd.png)
