### ISSUE TITLE
Table conversion issues

### ISSUE THREAD

**Issue by DeanStra** [dothinking/pdf2docx#136]
Hi I'm new to posting on Github so apologies for breaking any conventions and feedback appreciated!

I have some code which converts a pdf using python-pdf2docx using the following code

```
from pdf2docx import parse
pdf_file = 'A.pdf'
docx_file = 'Output_A.docx'
# convert pdf to docx
parse(pdf_file, docx_file, start=0, end=None)
```

and then adds text to the tables using python-docx. When I run the following code on the docx files

```
print(doc.tables[0].cell(0, 1).text)
print(doc.tables[1].cell(0, 1).text)
```

I find that for Output_A the first "table" python-docx recognises isn't a table (not a particular problem) and then it skips over the first two actual tables (a problem).

docx seems unable to recognise any tables in Output_B.

If I convert the files using Adobe or SmallPDFs online tools docx interprets the tables correctly. I'd like to turn the code into a little executable and the actually .docx code works great ... if it can detect the tables. Thank you in advance for helping.

p.s I made a [similar post](https://github.com/python-openxml/python-docx/issues/1082) in the python--docx page

[A.pdf](https://github.com/dothinking/pdf2docx/files/8693259/A.pdf)

[B.pdf](https://github.com/dothinking/pdf2docx/files/8693260/B.pdf)

[Output_A.docx](https://github.com/dothinking/pdf2docx/files/8693255/Output_A.docx)

[Output_B.docx](https://github.com/dothinking/pdf2docx/files/8693256/Output_B.docx)

**Comment by dothinking** [comment]
> Hi I'm new to posting on Github so apologies for breaking any conventions and feedback appreciated!

Welcome! I saw your email but sorry for didn't get time to handle it. It's great you post the issue here, so can help more people who might have similar issues.

> I find that for Output_A the first "table" python-docx recognises isn't a table (not a particular problem) and then it skips over the first two actual tables (a problem).

The first page is parsed to be a big table with implicit table borders. The first two actual tables are now "child-tables" in cell level, while `doc.tables` gets only tabkes in document/top level. See picture below with the outer border lines turn on.

> docx seems unable to recognise any tables in Output_B.

Output_B seems not the output of `pdf2docx`, but another online converter. So, it's probably an issue from `python-docx` scope. I didn't look much into it.

![图片](https://user-images.githubusercontent.com/13885442/169198617-89d22348-6f66-45cc-b7d6-632212c080fe.png)

**Comment by dothinking** [comment]
> If I convert the files using Adobe or SmallPDFs online tools docx interprets the tables correctly. 

Definitely, `pdf2docx` has significant limitation and improving space, compared to such famous comercial converters. Thanks for providing these test cases, which would help for the future improments.

> if it can detect the tables. Thank you in advance for helping.

If your purpose is to extract tables, especially such simple and full-bordered tables like your sample files,  `pdf2docx` could do it directly. For more complicated cases, other python libraries like `Camelot` and `pdfplumber` seems do a better job.

Taking `A.pdf` for example,

```python
from pdf2docx import Converter

cv = Converter('A.pdf')
tables = cv.extract_tables() # only explicit tables
cv.close()
```

Now, `tables` is a list of extracted tables like `[table1, table2, ...]`. 

```
>>> len(tables)
9
```

For each `table`, it is a 2d list for each row and cell, `[ [cell1, cell2, ...], row 2, ...]`. Taking first table for example,

```
>>> table = tables[0]
>>> table[0][0] # first cell
'1A '
>>> table[0] # first row
['1A ', 'Stephanie Kwolek is best known as the inventor of what synthetic fibre, used in many applications including bulletproof vests due to its very high tensile strength? ', 'Kevlar ']
```

**Comment by dothinking** [comment]
Closed for now. Feel free to reopen it if any further comments.

**Comment by sisrfeng** [comment]
What about base pdf2docx on pdfplumber instead of pymupdf?
