### ISSUE TITLE
太多小图片导致转换进程卡住

### ISSUE THREAD

**Issue by Priest2wyw** [dothinking/pdf2docx#138]
[5e2f116c-8126-4d9d-8d6a-03e004794ad3.PDF](http://disc.static.szse.cn/download/disc/disk03/finalpage/2022-05-12/5e2f116c-8126-4d9d-8d6a-03e004794ad3.PDF)

你好，我在使用过程中，发现有少数文件会出现卡死状况（概率<1/1000）,例如上面文件的第4页。目前已经将原因锁定在`ImagesExtractor.py`中`extract_images`：
```python
# step 2: group by intersection
fun = lambda a, b: a[0].intersects(b[0]) #出现问题
groups = ic.group(fun)
```

主要是`group`函数使用的` O(n^2) method`一般假设`n<1000`，但是在该文件第四页中 `n=123545`，时间过长。我现在还在努力的读源码，发现为啥会出现这种情况，看看如何解决。如果作者大大能够提供一定的帮助，我会非常感激。

**Comment by dothinking** [comment]
感谢提出问题、提供样例以及你的分析！

你的分析完全正确。你列出的那段代码本意：根据是否重叠（或邻近）把一些细小的图片拼接为完整的大图。针对的场景：扫描的一页图片有可能人眼看起来是一张大图，但实际被拆分成了许多小图片。而你的案例中，第四页表格中的**虚线的每一个点**居然都是一张图片！这样成千上万的图片确实让O(n^2)的方法崩溃了。

我想当然以为一页PDF怎么着都不会出现1000张图片，没想到以这种形式遇到了。直接的一个方法是把较小的图片过滤掉，但是会影响表格的样式（虚线边框不见了）。我这两天抽空试试。

**Comment by Priest2wyw** [comment]
邮件已收到

**Comment by Priest2wyw** [comment]
> 感谢提出问题、提供样例以及你的分析！
> 
> 你的分析完全正确。你列出的那段代码本意：根据是否重叠（或邻近）把一些细小的图片拼接为完整的大图。针对的场景：扫描的一页图片有可能人眼看起来是一张大图，但实际被拆分成了许多小图片。而你的案例中，第四页表格中的**虚线的每一个点**居然都是一张图片！这样成千上万的图片确实让O(n^2)的方法崩溃了。
> 
> 我想当然以为一页PDF怎么着都不会出现1000张图片，没想到以这种形式遇到了。直接的一个方法是把较小的图片过滤掉，但是会影响表格的样式（虚线边框不见了）。我这两天抽空试试。

这谁想得到......我分析出来123545张照片时候，还找了半天哪来的照片，没想到是虚线的点。

**Comment by dothinking** [comment]
暂时采用滤掉小图片（例如面积小于2x2=4）的解决方法吧：

找到`ImagesExtractor.py`中`extract_images`方法如下片段部分，增加一行图片面积的判断。修改后，测试第四页，由之前的卡死减为4s左右。

```python
for item in self._page.get_images(full=True):
    # image item: (xref, smask, width, height, bpc, colorspace, ...)
    item = list(item)
    item[-1] = 0            
    
    # find all occurrences referenced to this image            
    rects = self._page.get_image_rects(item)
    unrotated_page_bbox = self._page.cropbox # note the difference to page.rect
    for bbox in rects:
        if bbox.get_area()<=4: continue  # <----- 过滤掉小图片

        # ignore images outside page
        if not unrotated_page_bbox.intersects(bbox): continue

        # collect images
        ic.append((bbox, item))
```

**Comment by Priest2wyw** [comment]
邮件已收到

**Comment by Priest2wyw** [comment]
邮件已收到
