### ISSUE TITLE
'Page' object has no attribute 'rotationMatrix'

### ISSUE THREAD

**Issue by sksksksy** [dothinking/pdf2docx#141]
环境：anaconda python3.7，pip 20.0.2

步骤：

1.使用pip install pdf2docx安装后
2.新建一个python文件，写入以下代码：
`from pdf2docx import Converter

def extract_table(file_path):
    """
    打印被抽取表格的数据结构
    :param file_path: pdf文件路径
    :return: void
    """
    cv = Converter(file_path)
    tables = cv.extract_tables(start=0, end=1)
    cv.close()
    for table in tables:
        print(table)

if __name__ == '__main__':
    pdf_file = "表格测试1026.pdf"
    extract_table(file_path=pdf_file)
`
3.运行时出现错误：'Page' object has no attribute 'rotationMatrix'
![image](https://user-images.githubusercontent.com/31823704/174751412-20b7b161-b432-48a3-98cc-0c1f49d6be0d.png)

pip 下载的包目录：
![image](https://user-images.githubusercontent.com/31823704/174751907-5c51d595-917b-4361-b80f-f7f028478500.png)

**Comment by dothinking** [comment]
感谢反馈，几天前也有其他人遇到相同的问题 #139 。

错误原因是新版的上游依赖库`PyMuPDF`修改了属性：`rotationMatrix` -> `rotation_matrix`，我将在下一个版本中更新。

目前可以手动修改一下：根据第一张图中最后的错误提示，找到`RawPage.py`的第279行，把原始的

```python
Element.set_rotation_matrix(self.fitz_page.rotationMatrix)
```

改为

```python
Element.set_rotation_matrix(self.fitz_page.rotation_matrix)
```

**Comment by sksksksy** [comment]
好的，谢谢
