### ISSUE TITLE
'created' timestamp seems very low; regarding as unix timestamp

### ISSUE THREAD

**Issue by benemorphy** [dothinking/pdf2docx#147]
win10环境，python 3.8

[INFO] Start to convert 01.pdf
[INFO] [1/4] Opening document...
[INFO] [2/4] Analyzing document...
[WARNING] 'created' timestamp seems very low; regarding as unix timestamp
[ERROR] 'closePath'

**Comment by dothinking** [comment]
感谢反馈。

问题原因是一个依赖库`pymupdf`升级到了1.20+版本，我还没来得及同步更新一些变动的地方。

请暂时先参考 #146 的临时修复方法，周一前我会更新一个修复的版本。

**Comment by dothinking** [comment]
已发布`v0.5.5`修复此问题：

```
pip install pdf2docx --upgrade
```
