### ISSUE TITLE
Error I can't handle

### ISSUE THREAD

**Issue by neluckoff** [dothinking/pdf2docx#148]
I have a standard code that is used in all examples

from pdf2docx import Converter

cv = Converter(pdf_file)
cv.convert(docx_file, start=0, end=None)
cv.close()

But I've run into a problem that I can't solve. The code just can't get the text from my PDF file, it doesn't have a password.

Exception: No parsed pages. Please parse page first.

Parsing Page 1: 1/7...
Ignore page due to error: 'Page' object has no attribute 'getText'
Parsing Page 2: 2/7...
...

**Comment by dothinking** [comment]
Which version of `pdf2docx` do you use? Seems you're using an old version which is not compatible with the version of its dependence library `PyMuPDF`.

**Comment by neluckoff** [comment]
You were right, I apologize for such a stupid meaning.
