### ISSUE TITLE
Cell background color not working

### ISSUE THREAD

**Issue by GFourns** [dothinking/pdf2docx#149]
Hi,

Thanks for your great library, it is working very nicely in most cases and I love it.
However, with the particular file attached (which is an audit report generated from HTML file), the background color of div inside the last table (page 4, 2nd column, first label, that are green/orange/red) is not rendered correctly (no background color in docx).
It is weird because others elements in the table (like row with colspan 2 - acting as table sections) are rendered with background.

Can you provide help or explanation on how to render the background color of this kind of element?

Thanks in advance for your answer and support.

[report_8c17a2df-4c14-4e2a-942f-e104cfe664b2.pdf](https://github.com/dothinking/pdf2docx/files/9084914/report_8c17a2df-4c14-4e2a-942f-e104cfe664b2.pdf)

**Comment by dothinking** [comment]
Hi, GFourns,

Thanks for providing the test file, and sorry for the late reply.

> others elements in the table (like row with colspan 2 - acting as table sections) are rendered with background

It's the normal case, the entire cell is rendered with background color.

> the background color of div inside the last table (page 4, 2nd column, first label, that are green/orange/red) is not rendered correctly

Comparing to the normal case, just part of this cell is rendered with background, so a nest table parsing should deep into this cell. However, it's limited to avoid infinite stream table detection. So, a workaround is to break this limitation.

Navigate to `TablesConstructor.py` in your python library installation path, e.g., .../site-packages/pdf2docx/table/TablesConstructor.py, change codes around Line 196,

```python
# Attention: avoid further infinite stream table detection.
# Generally, a 1x1 stream table nested in a table cell is of no use
if isinstance(self._parent, Cell) and table.num_cols*table.num_rows==1:
    continue
```

to

```python
# Attention: avoid further infinite stream table detection.
# Generally, a 1x1 stream table nested in a table cell is of no use
if isinstance(self._parent, Cell) and table.num_cols*table.num_rows==1 and table[0][0].bg_color is None:
    continue
```

**Comment by dothinking** [comment]
Note that an extra-table with only one cell is inserted to the orginal cell. 

![图片](https://user-images.githubusercontent.com/13885442/181933690-7e157d19-2d1b-4c3d-96be-e234b6013cf7.png)

**Comment by GFourns** [comment]
Hi dothinking,

Thanks for your detailled reply. Now it is working perfectly. Thanks a lot!

**Comment by heweisheng** [comment]
if one line and parent not cell maybe drop it
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/9109d7c5-1a5b-4303-bc25-4a42ef71ba65)

**Comment by heweisheng** [comment]
fix:
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/2f61493c-e20d-4f3b-8636-7f709dc7ccb5)
fix result:
![image](https://github.com/ArtifexSoftware/pdf2docx/assets/37769332/da265c61-53e6-4438-98b7-926a9856ea3e)


test file
[testocr.pdf](https://github.com/ArtifexSoftware/pdf2docx/files/15455975/testocr.pdf)
