### ISSUE TITLE
How to output merged cells?

### ISSUE THREAD

**Issue by huiyanghu12** [dothinking/pdf2docx#150]
请问下怎么输出合并的单元格呢？
我看这个 https://dothinking.github.io/pdf2docx/quickstart.table.html，
按照示例跑出来的结果，如果是合并的单元格，只会第一个列显示，其他的格子数据是None。
怎么解决呢？

How to output merged cells?
I read this https://dothinking.github.io/pdf2docx/quickstart.table.html,
According to the result of the example, if it is a merged cell, only the first column is displayed, and the other grid data is None.
How to solve it?

**Comment by dothinking** [comment]
如果是合并单元格，仅在合并区域的第一个单元格显示内容，其余被合并区域确实是`None`，不知道你预期是怎样的输出？

**Comment by dothinking** [comment]
下面从深入`pdf2docx`内部数据结构的角度演示这个问题。

- 解析PDF后得到每一页`Page`，其结构包含章节、分栏等，参考[这页](https://dothinking.github.io/pdf2docx/pdf2docx.page.Page.html)

- 一个分栏内包含一系列`Block`类型结构如段落和表格，其中表格`TableBlock`包含行、单元格等，参考[这页](https://dothinking.github.io/pdf2docx/pdf2docx.table.TableBlock.html)


- 单元格`Cell`有一些属性，其中`merged_cells`是一个元组，表示合并的行列数，例如
    - 你的例子中的第一个单元格，`merged_cells=(2,1)`表示合并掉了2行1列
    - 正常单元格是`merged_cells=(1, 1)`，表示自身
    - 被合并掉的单元格`bool(cell)=False`

针对你给出的例子：

```python
from pdf2docx import Converter


cv = Converter('default.pdf')

# 以第一页为例
cv.parse(start=0, end=1, **cv.default_settings)
page = cv.pages[0]

# 获取第一页所有显式表格
tables = []
for section in page.sections:
    for column in section:
    	tables.extend(column.blocks.lattice_table_blocks)

# 第一个表格为例
table = tables[0]


# 把单元格分为三类：
# - merging：合并单元格，例如“本月”和“年累计”
# - merged：被合并掉的单元格，例如“本月”占了3个单元格位置，后面两个即为被合并单元格
# - normal：其余为正常单元格
def merging_status(cell):
	if not cell: return 'merged'
	if cell.merged_cells==(1,1): return 'normal'
	return 'merging'


# 检查单元格状态
print('index, cell status, text')
for i,row in enumerate(table):
	for j,cell in enumerate(row):
		print((i,j), merging_status(cell),  cell.text)
```

输出：

```
index, cell status, text
(0, 0) merging 结算项目
(0, 1) merging 本月
(0, 2) merged None
(0, 3) merged None
(0, 4) merging 年累计
(0, 5) merged None
(0, 6) merged None
(1, 0) merged None
(1, 1) normal 使用量
(1, 2) normal 单价
(1, 3) normal 费用
(1, 4) normal 使用量
(1, 5) normal 单价
(1, 6) normal 费用
(2, 0) normal 结算合计
(2, 1) normal 1000
(2, 2) normal 5
(2, 3) normal 5000
(2, 4) normal 10000
(2, 5) normal 5
(2, 6) normal 50000
```

**Comment by huiyanghu12** [comment]
太感谢了！！！
