### ISSUE TITLE
Tables extraction from DOCX

### ISSUE THREAD

**Issue by GPrakruth** [dothinking/pdf2docx#154]
Hi,

PDF files are converted to DOCX and then tables are extracted from DOCX.
There are hidden columns and hidden text in the tables.
Is there a way to ignore the hidden columns and text during conversion?
Can the table structure be maintained during conversion of pdf to docx ignoring the hidden content and columns

**Comment by dothinking** [comment]
Could you please upload a test pdf file to show what hidden columns and hidden text mean?

This library supports to extract tables (with explicit borders) directly from pdf. Is this #136 relevant to your issue?

**Comment by GPrakruth** [comment]
Thankyou for reaching out, can the document be shared in private?
this is because the document contains financial information which cannot be share publicly?

**Comment by dothinking** [comment]
How about my gmail (train8808)? 

I'll keep it private and use it only for this issue tracking purpose.

**Comment by GPrakruth** [comment]
Hi,

This is for checking purpose. Can you please confirm me if this is correct
email ID so that I can share the document here.

Regards,
Prakruth

**Comment by dothinking** [comment]
Confirmed. This e-mail address could be find from my github profile as well.

Thanks for your trust.

**Comment by dothinking** [comment]
As checked, with the default settings, some empty cells are created unexpectedly. It's because the background shadings in source pdf are composed of normal shadings and "thin" pieces, as red arrows marked, where the "thin" shadings are counted as table borders. So, extra cells are parsed unexpectedly.



![图片](https://user-images.githubusercontent.com/13885442/181916696-bfec9743-6dba-4c4a-9da3-cf70ed862c05.png)


![图片](https://user-images.githubusercontent.com/13885442/181916648-ffcbb3ce-ad73-4416-a048-c33b79d76176.png)

**Comment by dothinking** [comment]
A parameter, `max_border_width`, is provided to control the maximum width of potential table borders. The default value is 6.0pt, seems quite large in this case. So, set a smaller value, e.g. `max_border_width=2.0`, can fix this issue. 

```python
from pdf2docx import Converter

pdf_file = '/path/to/sample.pdf'
docx_file = '/path/to/sample.docx'

# convert page 245, 246 to docx for example
cv = Converter(pdf_file)
cv.convert(docx_file, start=245, end=247, max_border_width=2.0) 
cv.close()
```

**Comment by dothinking** [comment]
> PDF files are converted to DOCX and then tables are extracted from DOCX.

`pdf2docx` supports to extract tables directly from PDF.

```python
from pdf2docx import Converter

pdf_file = '/path/to/sample.pdf'
cv = Converter(pdf_file)
tables = cv.extract_tables(start=245, end=247, max_border_width=2.0)
cv.close()

# print cell contents
for table in tables: print(table)
```

**Comment by GPrakruth** [comment]
Thankyou for the solution, we are now able to extract data correctly
