### ISSUE TITLE
UnicodeDecodeError problem when converting Chinese pdf

### ISSUE THREAD

**Issue by ddzzhen** [dothinking/pdf2docx#155]
First of all, this is useful and I appreciate it!

I have a problem converting Chinese pdf, it seems to be an encoding problem, but I'm not sure and can't find a solution.
[file 1](https://github.com/ddzzhen/resources_forcode/blob/main/1.pdf)
[file 3](https://github.com/ddzzhen/resources_forcode/blob/main/3.pdf)

The font encoding of file 1 is `GBK-EUC-H`, it cannot be converted to docx, the error encountered is 
```
>>> cv = Converter(pdf_file)
>>> cv.convert(docx_file)
[INFO] Start to convert 1.pdf
[INFO] [1;36m[1/4] Opening document...[0m
[INFO] [1;36m[2/4] Analyzing document...[0m
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
The above exception was the direct cause of the following exception:
SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
```
The font encoding of file 3 is `Identity-H`, which converts to docx normally.

The python environment is win10, and Ubuntu20 has also been tested, and the results are consistent.

In addition, using online services such as `https://pdf2docx.com/zh/`, both file 1 and file 3 can be converted normally. After they are converted successfully, the fonts are modified to Song Dynasty.
I hope there is a way to modify the encoding or convert it so that it can be converted normally, thank you.

**Comment by dothinking** [comment]
Thanks for reporting this issue.

It's an upstream library issue for some unusual Chinese fonts. Please see workaround [here](https://github.com/dothinking/pdf2docx/issues/144#issuecomment-1200132754).

> After they are converted successfully, the fonts are modified to Song Dynasty.

Not like pdf embedding all used fonts, docx uses only the fonts installed in your system. So, generally, the converter will change unusual fonts used in pdf to common fonts, e.g., Song, in this case.

**Comment by ddzzhen** [comment]
After testing it solved the problem, thank you very much!
