### ISSUE TITLE
读取表格时间异常且读取错误 A Runtime error occurred when reading the table

### ISSUE THREAD

**Issue by alonewhitex** [dothinking/pdf2docx#158]
当读取表格线不统一的表格时，会花费超长时间（大概需要几个小时以上），且读取出来的表格是错乱的。
When reading a table with inconsistent lines, it takes a long time (probably more than a few hours) and the table is read out of order.

pdf已经发送。The PDF has been sent.

**Comment by alonewhitex** [comment]
还有一个问题，如果我使用最新版本的pdf2docx(pdf2docx==0.5.5)转换上述同一个文件时会报错：
Another problem is that I get an error if I use the latest version of pdf2docx(pdf2docx==0.5.5) to convert the above files:
'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
但若我使用pdf2docx==0.5.3，PyMuPDF==1.19.0就可以正常转换，不知道是不是上游库的问题。
But if I use pdf2docx==0.5.3, PyMuPDF==1.19.0, the file can be converted normally. I don't know if it is the upstream library problem.

**Comment by dothinking** [comment]
感谢提供测试文件。

> 当读取表格线不统一的表格时，会花费超长时间（大概需要几个小时以上），且读取出来的表格是错乱的。

具体原因参考这个问题说明 #138 -> 一般情况下我们人眼看到PDF表格边框是由`形状`（如线条、矩形等）组成的，而你的例子比较特殊，表格虚线边框的每一个点都是一张小图片，在计算图片的重叠状态时会因为图片太多而花费非常长的时间，并且这些图片不会作为表格边框来解析，最终结果也不正确。

这个问题在新发布的版本 `v0.5.6` 中解决了一半：通过过滤掉小图片避免超时，但是还没解决图片作为表格边框来解析的问题，因此最终表格结构和PDF还有一些差异。

> 还有一个问题，如果我使用最新版本的pdf2docx(pdf2docx==0.5.5)转换上述同一个文件时会报错

确实是上游库的问题，`v0.5.4`版本为了解决 #132 ，引入了上游库的一个函数导致了这个问题；所以你使用低于`0.5.4`的版本没问题。这个问题一并在 `v0.5.6` 版本中处理了，注意是处理了而不是完美解决，但是适用于绝大多数场景，具体参考 #144。

综上，请尝试`v0.5.6`版本，可以解决超时和报错的问题，但是表格解析尚待进一步处理。

```bash
pip install pdf2docx --upgrade
```

**Comment by alonewhitex** [comment]
> 综上，请尝试`v0.5.6`版本，可以解决超时和报错的问题，但是表格解析尚待进一步处理。

谢谢您的详细回复，升级到v0.5.6确实有所解决，但转换结果依然会有些问题。
但不管怎样，这个库非常好用，感谢您的开发！
