### ISSUE TITLE
[ERROR] Ignore page 8 due to making page error: float division by zero

### ISSUE THREAD

**Issue by wiidede** [dothinking/pdf2docx#190]
font_size maybe 0. While i meet the self.size is 0.1, and then the font_size will become 0.

i think we should judge the font_size's value, sometimes, it can be 0

https://github.com/dothinking/pdf2docx/blob/3c3f7554a367f335368a79dd8c9d39ccd6f5f996/pdf2docx/text/TextSpan.py#L409-L416

```bash
Exception has occurred: ZeroDivisionError
float division by zero
  File "C:\Users\wdd\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2docx\text\TextSpan.py", line 416, in _set_text_format
    scale = self.size / font_size
```

**Comment by dothinking** [comment]
Thanks for your contribution. The PR is merged.
