### ISSUE TITLE
Can opencv-python dependency be switched to opencv-python-headless 

### ISSUE THREAD

**Issue by Code4SAFrankie** [dothinking/pdf2docx#224]
Can the opencv-python dependency be switched to opencv-python-headless for use with docker and Azure App services?

**Comment by embiem** [comment]
Hey, I had the same issue. I went ahead and created a fork that's using the headless version of opencv-python: https://pypi.org/project/pdf2docx-headless/

**Comment by dothinking** [comment]
Thanks for this good suggestion. opencv-python-headless switching is on the way.

**Comment by dothinking** [comment]
`v0.5.8` was released with `opencv-python` dependency switched to `opencv-python-headless`.
