### ISSUE TITLE
AttributeError: module 'pdf2docx.common.utils' has no attribute 'reset_paragraph_format'

### ISSUE THREAD

**Issue by wangbohan2000** [dothinking/pdf2docx#28]
When I convert PDF to docx, I have this problem.

**Comment by dothinking** [comment]
It's due to changed module name recently. Thank you for reporting this. 

Now it's fixed in version `0.3.1`.  Please upgrade your installation and have a try. 

`pip install --upgrade pdf2docx`

**Comment by dothinking** [comment]
would close this issue. Feel free to open it if necessary.
