### ISSUE TITLE
[Feature] 部分连贯字体看起来粗细不同

### ISSUE THREAD

**Issue by smilelight** [dothinking/pdf2docx#38]
如图：

![pdf2docx解析结果粗细](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/pdf2docx解析结果粗细.png)

原文截图：

![pdf2docx字体粗细原文截图](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/pdf2docx字体粗细原文截图.png)
令我感到好奇的是“一、引论”那一行虽然人肉眼看上去字体明显不同，但是在Word中样式都是加粗的且font-family统一。
您在Pdf2docx开发概要中提到的[`Solid Documents`](https://solidframework.net/)看起来没有这个问题，但是其也丢失掉了字体加粗的样式，如图：

![smallpdf解析pdf结果](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/smallpdf解析pdf结果.png)
请问这个功能pdf2docx可以实现吗，使用的是版本为0.3.4（目前最新）的pdf2docx。

测试文档链接地址：

[pdf测试文档](http://www.lightsmile.cn:5666/test_pdf/%E8%87%AA%E5%B7%B1%E7%9A%84%E6%96%87%E6%A1%A3.pdf)

**Comment by dothinking** [comment]
谢谢发现这个问题并提供详细的测试信息。这个是中文字体名称匹配的问题，恰好我在周末进行了修复 :) 今天之内会更新一个小版本。

**问题原因：**

以`引论`为例，`PyMuPDF`得到原始的字体信息`MicrosoftYaHei`，然后`python-docx`创建文档时直接设置`MicrosoftYaHei`字体。虽然从名称看我们知道是`微软雅黑`，但Word却无法识别，进而自动替换为一种亚洲文字字体`MS MinCho`，可是这是日本文字字体。

**当前解决方案：**

为常见的中文字体名称建立一个匹配字典，例如

```python
# font name mapping
DICT_FONTS = {
    'SimSun': '宋体', 
    'SimHei': '黑体', 
    'MicrosoftYaHei': '微软雅黑', 
    ...
}
```

**Comment by smilelight** [comment]
好的，感谢您的回复与解答
