### ISSUE TITLE
[Feature] 段落换行拼接功能

### ISSUE THREAD

**Issue by smilelight** [dothinking/pdf2docx#39]
还有一个关于段落换行的问题，测试文档链接：[测试文档](http://www.lightsmile.cn:5666/test_pdf/%E8%87%AA%E5%B7%B1%E7%9A%84%E6%96%87%E6%A1%A3.pdf)。

原文如图：
![pdf换行问题原文](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/pdf换行问题原文.png)

使用pdf2docx解析结果为：
![pdf解析换行pdf2docx](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/pdf解析换行pdf2docx.png)
可见每行后面都跟有一个回车换行符，对应Word文档链接：[pdf2docx解析结果](http://www.lightsmile.cn:5666/test_pdf/%E8%87%AA%E5%B7%B1%E7%9A%84%E6%96%87%E6%A1%A3-pdf2docx.docx)。

使用smallpdf解析结果为：
![pdf换行解析smallpdf](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/pdf换行解析smallpdf.png)
可见段落是连续的，之间并无回车换行符，对应Word文档链接：[samllpdf解析结果](http://www.lightsmile.cn:5666/test_pdf/%E8%87%AA%E5%B7%B1%E7%9A%84%E6%96%87%E6%A1%A3-smallpdf.docx)。

这个问题看起来不太容易处理，不过请问您考虑今后增加该功能吗

**Comment by dothinking** [comment]
在第一个版本`0.0.1`中考虑过这个`自动换行`问题：对于PDF中提取出来的空间上的两行，如果当前行**理论**剩余空间不足以容纳下一行的第一个字符，表明Word中可以自动换行，于是省略这两行之间的换行符（Shift+Enter），也就是你图片中行尾的符号。

然而现实问题是上面计算的**理论**距离是基于PDF提取的数据，而在Word中渲染后可能是不同的值，导致实际判断换不换行有时正确有时失败。所以，后续版本取消了这个判断，统一用换行符处理。

这样处理达到了“看起来像”的效果，不过语义上确实有割裂，但好在换行符（Shift+Enter）不同于回车（Enter），这两行在Word中仍属于同一个段落。后续如果有文本处理上的需求，可以在提取段落内容后再过滤一遍`\n`。

如果有了新的想法，我会继续考虑这个自动换行的问题。

**Comment by smilelight** [comment]
好的，感谢您的耐心回复~
