### ISSUE TITLE
表格边框线缺失

### ISSUE THREAD

**Issue by Angelucky** [dothinking/pdf2docx#46]
你好边框线缺失的这个问题可以解决吗

**Comment by Angelucky** [comment]
pdf转docx候表格上面的边框线缺失有的是左右的边框有的是上下的边框

**Comment by dothinking** [comment]
方便给个具体的例子文件吗？谢谢
对于边框线不全的表格例如三线/四线表，确实可能出现你说的问题。

**Comment by Angelucky** [comment]
你好，怎么给你发示例文件，可以给个联系方式吗

**Comment by dothinking** [comment]
请尝试最新版是否解决你的问题。暂时关闭，如问题依旧存在，请随时打开。
