### ISSUE TITLE
import parse: start = 1

### ISSUE THREAD

**Issue by enzococca** [dothinking/pdf2docx#48]
Is it possible set start = 1 and not 0 like first page? I mean in the global setting

E

**Comment by dothinking** [comment]
Thank you for this user friendly suggestion. It's not complicated though, I don't have a good practice to do such global setting. So any suggestion, or could you please send a PR? The entrance [main.py](https://github.com/dothinking/pdf2docx/blob/master/pdf2docx/main.py). Thank you in advance.
