### ISSUE TITLE
cannot import name 'parse' from 'pdf2docx'

### ISSUE THREAD

**Issue by Jalkhov** [dothinking/pdf2docx#55]
I try to run de example in the README.md and give that error.

```
from pdf2docx import parse

pdf_file = '09_0370.pdf'
docx_file = 'File.docx'

# convert pdf to docx
parse(pdf_file, docx_file, start=0, end=1)
```

What's wrong?

**Comment by dothinking** [comment]
Have you installed the library first? After that it should work. Please refer to `Installation` section in README.md. 

If not, say you'd like to use the source code directly, you need to import `parse` like:

```python
from pdf2docx.main import parse
```

**Comment by Jalkhov** [comment]
![2020-10-20 16_48_51](https://user-images.githubusercontent.com/36505934/96642481-3aa2cc80-12f4-11eb-8fac-e8399c04d578.png)
Yes, the library is installed, I do a pip freeze and it appears in the list, applying the method of you said it works well, but I do not know, it seems to me something little optimal to include the folders in my project, I use window 10 x32 Bits in case it is useful.

**Comment by dothinking** [comment]
See Jalkhov's comment above, check whether your have `pdf2docx.py`, which is conflict with the library name `pdf2docx`.
