### ISSUE TITLE
Generate all pages from file

### ISSUE THREAD

**Issue by Jalkhov** [dothinking/pdf2docx#56]
A way for process all pages from a file without set a range? Example:

`parse(pdf_file, docx_file, start=0, end=pdf2docx.allpages())`

**Comment by dothinking** [comment]
If you omit `start` and `end`, it'll convert all pages as you suggested, just like:

```python
parse(pdf_file, docx_file)
```

By default, the converting pages start from the first page, and end with the last page. So you can use bother/either/none of these two arguments at your convenience.
