### ISSUE TITLE
ERROR: Could not consume arg: test.pdf

### ISSUE THREAD

**Issue by Beckett8888** [dothinking/pdf2docx#60]
ERROR: Could not consume arg: test.pdf
Usage: pdf2docx <command>
  available commands:    convert | table

For detailed information on this command, run:
  pdf2docx --help

**Comment by dothinking** [comment]
Sorry that the master branch is a bit ahead of the README page. The command was changed to

```
pdf2docx convert pdf_file ...
```

As you can see, **convert** was inserted, but the rest is same. 

Or you can install the released v0.4.6 version per `pip` and follow the command as README said.
