### ISSUE TITLE
中文乱码？

### ISSUE THREAD

**Issue by shumintao** [dothinking/pdf2docx#62]
中文乱码？怎么解决？

**Comment by dothinking** [comment]
方便提供测试文件吗？

**Comment by shumintao** [comment]
![image](https://user-images.githubusercontent.com/26895243/99349693-93f02280-28d7-11eb-8147-90391a7da26f.png)

**Comment by dothinking** [comment]
你这是图片，目前不支持扫描文件的转换

**Comment by dothinking** [comment]
看到 #63 提供的测试文件，才理解你的问题。

`pdf2docx`是靠上游python库`PyMuPDF`提取PDF内容的，`PyMuPDF`本身支持中文，但是某些PDF文件可能缺少cmaps表——将CJK（中日韩）字符映射到unicode字符的规则，结果导致无法正确获取文本。

> I have multiple pdf files without 'toUnicode' cmap table. Absence of cmap table restricts me from copying the text from pdf files.

> For some fonts in some PDFs some characters cannot be extracted correctly, because their CMap / ToUnicode doesn't make sense or is incomplete

`PyMuPDF`项目相关的issue：

- https://github.com/pymupdf/PyMuPDF/issues/87
- https://github.com/pymupdf/PyMuPDF/issues/365
- https://github.com/pymupdf/PyMuPDF/issues/530

由于是PDF自身的问题，且尚未发现通用的解决方案，`pdf2docx`对这个问题无法提供支持。

**Comment by JorjMcKie** [comment]
Just as a comment from the outside:
This type of problem can only be solved by using an OCR program like Tesseract. There is Python repo available, which does a good job on this: https://github.com/jbarlow83/OCRmyPDF, I have tried it myself.

There also is a way to incorporate Tesseract directly in MuPDF v1.18.0 (which I do not use yet in PyMuPDF).
