### ISSUE TITLE
程序报 ValueError: no valid image found错误

### ISSUE THREAD

**Issue by leyiwang** [dothinking/pdf2docx#63]
测试样例：链接: https://pan.baidu.com/s/1yP1v554PKxk0UAkSpk8CHw 提取码: knvt 
在进行格式转换过程中，报了ValueError: no valid image found错误，辛苦看下哈
dev分支转换过程输出如下：
```
Parsing Pages: 154/297 per CPU 2...Ignore Line "<image>" due to overlap
Parsing Pages: 77/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 232/297 per CPU 3...Ignore Line "<image>" due to overlap
Parsing Pages: 168/297 per CPU 2...Ignore Line "<image>" due to overlap
Parsing Pages: 88/297 per CPU 1...Ignore Line "�" due to overlap
Parsing Pages: 185/297 per CPU 2...Ignore Line "<image>" due to overlap
Parsing Pages: 186/297 per CPU 2...Ignore Line "<image>" due to overlap
Parsing Pages: 101/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 191/297 per CPU 2...Ignore Line "<image>" due to overlap
Parsing Pages: 263/297 per CPU 3...Ignore Line "<image>" due to overlap
Parsing Pages: 109/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 111/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 268/297 per CPU 3...Ignore Line "<image>" due to overlap
Parsing Pages: 124/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 285/297 per CPU 3...Ignore Line "<image>" due to overlap
Parsing Pages: 289/297 per CPU 3...Ignore Line "<image>" due to overlap
Parsing Pages: 224/297 per CPU 2...Ignore Line "<image>" due to overlap
Parsing Pages: 138/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 144/297 per CPU 1...Ignore Line "<image>" due to overlap
Parsing Pages: 146/297 per CPU 1...Ignore Line "<image>" due to overlap
```
@dothinking

**Comment by dothinking** [comment]
多谢指出问题和提供案例。测试了一下，很遗憾，`pdf2docx`无法较好地转换你的文档。

> 程序报 ValueError: no valid image found错误

已经发布的`0.4.6`版本确实对图片的支持存在不足，例如仅支持常规的RGB颜色空间，而你第二页的图片是ICCBased。所以在`dev`分支做了一些改进尝试，目前还在进行中。

**Comment by dothinking** [comment]
最主要的还是**部分中文乱码问题**：

`pdf2docx`本身是支持中文的，但是你提供的PDF文件不知是文件损坏还是版权保护有意为之，一些中文字符读出之后显示乱码。查找资料的解释是PDF文件缺少`cmaps`表——将`CJK`（中日韩）字符映射到`unicode`字符的规则，结果导致无法正确获取文本。

例如手动复制第7页前言第一句话“欢迎阅读本书的第2版”，粘贴后就成了：
```
൓ᤀ᫝ឳ本书ᄉኃ2版
```

如果尝试在线的PDF转word网站，例如smallpdf，结果也是一样的。

---

你的测试文件让我理解了 @shumintao 提的一个问题 https://github.com/dothinking/pdf2docx/issues/62

**Comment by leyiwang** [comment]
> 确实对图片的支持存在不足，例如仅支持常规的RGB颜色空间，而你第二页的图片是ICCBased。所以在`dev`分支做了一些改进尝试，目前还在进行中。

了解了，加油！

**Comment by leyiwang** [comment]
> 最主要的还是**部分中文乱码问题**：
> 
> `pdf2docx`本身是支持中文的，但是你提供的PDF文件不知是文件损坏还是版权保护有意为之，一些中文字符读出之后显示乱码。查找资料的解释是PDF文件缺少`cmaps`表——将`CJK`（中日韩）字符映射到`unicode`字符的规则，结果导致无法正确获取文本。
> 
> 例如手动复制第7页前言第一句话“欢迎阅读本书的第2版”，粘贴后就成了：
> 
> ```
> ൓ᤀ᫝ឳ本书ᄉኃ2版
> ```
> 
> 如果尝试在线的PDF转word网站，例如smallpdf，结果也是一样的。
> 
> 你的测试文件让我理解了 @shumintao 提的一个问题 #62

确实，也尝试用了其他的工具和pymupdf的作者也进行了交流，目前确实还无法解析示例中复制乱码的pdf文档
