### ISSUE TITLE
你好，有没有办法就是在转word的时候某一页出现错误转不出来，跳过这个错误元素，继续往下执行

### ISSUE THREAD

**Issue by Angelucky** [dothinking/pdf2docx#67]
我出现错误是因为pdf里面有那种流程图之类的，然后会报一个
![image](https://user-images.githubusercontent.com/68835406/103050759-11dad400-45d0-11eb-8f13-ac73d3d5b8a0.png)

**Comment by dothinking** [comment]
多谢指出问题，请尝试更新一下版本`v0.5.0`

```bash
pip install --upgrade pdf2docx
```
