### ISSUE TITLE
Is there any way i can stop table parsing

### ISSUE THREAD

**Issue by monuminu** [dothinking/pdf2docx#68]
Hi Team

I have a requirement where i know we don't have tables in pdf . Is there any way i can stop having false positive tables and only ave paragraphs . In way this library will be so helpful for me .

**Comment by monuminu** [comment]
thanks for replying . I think better option would be have a flag to identify steam table only , lattice table only , stream lattice both , none.  In this way we can definitely have much more control about document conversion . unfortunately I can't share the document as it's organisation internal document .

**Comment by dothinking** [comment]
May I know your purpose using this lib, the pdf text only, or both text and layout (e.g. paragraph spacing, indentation and text format)? If you concern only the text, I'd suggest to use `PyMuPDF` directly, or similar pdf processing libs like `pikepdf`, `PyPDF`, `pdfminer`...

The lib extracts pdf text with an upstream lib `PyMuPDF`, and focuses on layout rebuilding, while stream table is responsible for the layout (split float layout into flow layout in each cell). The lib thinks it's necessary to if stream table exists in your docx. In this case, if turn it off, the layout rebuilding may fail.

**Comment by dothinking** [comment]
close this for now. feel free to reopen it if any new thoughts.

**Comment by monuminu** [comment]
Hey is there any way i can only have lattice table detection and switch off stream table detection .

**Comment by dothinking** [comment]
> Hey is there any way i can only have lattice table detection and switch off stream table detection .

As described before, stream table is required to rebuild the page layout. But if you don't care much about the layout, yes, you can switch it off. For now, you need to do it manually -> hard comment stream table parsing. Take version 0.5.1 for example, 

1. go to file `Layout.py`

```python
>>> import pdf2docx
>>> pdf2docx.page.Layout.__file__
'd:\\21_github\\pdf2docx\\pdf2docx\\page\\Layout.py'
```

2. go to method `_parse_layout_bottom_up()` (Line 119), then hard-comment stream table parsing as needed.

```python
def _parse_layout_bottom_up(self, settings:dict):
    '''Parse layout bottom-up: 
    
    * detect explicit tables first based on shapes, 
    * then stream tables based on original text blocks and parsed explicit tables;
    * move table contained blocks (text block or explicit table) to associated cell layout.
    '''
    # parse table structure/format recognized from explicit shapes
    self._table_parser.lattice_tables(
                    settings['connected_border_tolerance'],
                    settings['min_border_clearance'],
                    settings['max_border_width'])
    
    # parse table structure based on implicit layout of text blocks
    self._table_parser.stream_tables(
                    settings['min_border_clearance'],
                    settings['max_border_width'],
                    settings['float_layout_tolerance'],
                    settings['line_separate_threshold'])
```

> I think better option would be have a flag to identify steam table only , lattice table only , stream lattice both , none. In this way we can definitely have much more control about document conversion.

I concerned much about the function of stream table for page layout. But as suggested, flexible option of table parsing does accommodate more use cases. As seen in method `_parse_layout_bottom_up`, it's easy to add such flag in `settings`. Would do it in next version. 

Thank you so much for this good suggestion.

**Comment by dothinking** [comment]
`v0.5.2` is available in Pypi now, arguments `parse_lattice_table` and `parse_stream_table`, both True by default, should work for this issue. The usage might look like:

```python
from pdf2docx import Converter

pdf_file = '/path/to/sample.pdf'
docx_file = 'path/to/sample.docx'

# parse lattice tables only
cv = Converter(pdf_file)
cv.convert(docx_file, parse_stream_table=False)
cv.close()
```
