### ISSUE TITLE
Text in table

### ISSUE THREAD

**Issue by Qi-HuT** [dothinking/pdf2docx#71]
Why is the text obtained after conversion in the table?

**Comment by dothinking** [comment]
`pdf2docx` concerns both the text and its layout/format. Stream table (table without borders) helps to rebuild the page layout, so the text shown in pdf might be converted to content in table.

**Comment by Qi-HuT** [comment]
> `pdf2docx` concerns both the text and its layout/format. Stream table (table without borders) helps to rebuild the page layout, so the text shown in pdf might be converted to content in table.

sorry. So how do i extract the text?

**Comment by dothinking** [comment]
If you concern the text only, a better choice would be pdf library like `PyMuPDF`, `PyPDF4`, `pdfminner.six` ...

May I know what do you want to do with `pdf2docx`? It would be great if sharing a sample pdf file.

**Comment by Qi-HuT** [comment]
I just want to extract some sentences of word. I want to create a dataset.
![image](https://user-images.githubusercontent.com/46215418/109118170-5298ca00-7786-11eb-9c2f-585b37274f22.png)

**Comment by dothinking** [comment]
So you needn't to convert PDF to docx, but use pdf library to read text from PDF directly, e.g. `PyMuPDF`, `PyPDF4`, `pdfminer.six`.

**Comment by Qi-HuT** [comment]
ok，thank you. i will try the pdf library.
