### ISSUE TITLE
中文转换失败，chinese convert failed！

### ISSUE THREAD

**Issue by douyacun** [dothinking/pdf2docx#72]
my pdf :

[READEME.pdf](https://github.com/dothinking/pdf2docx/files/6044609/READEME.pdf)

after convert:

![image](https://user-images.githubusercontent.com/35790720/109189018-83045680-77ce-11eb-82a1-14717b2ddea8.png)

**Comment by dothinking** [comment]
感谢反馈问题和提供样例。问题原因是原始PDF文档存在问题，我用PDF编辑器`PDF-XChange`打开时显示：

![image](https://user-images.githubusercontent.com/13885442/109247511-077ec580-781f-11eb-90af-95b42d4d8e00.png)

通过`PDF-XChange`另存为一个新文件，编辑器自行修复了该问题（Adobe PDF阅读器另存为也可以）。然后再用`pdf2docx`转换可以得到正确结果（瑕疵：列表图标不是文本格式的，这里丢失了）:

![image](https://user-images.githubusercontent.com/13885442/109247876-a7d4ea00-781f-11eb-82a3-c7d4c9ac8aa4.png)

**Comment by dothinking** [comment]
这是一个很好的样例——原始PDF并不完美，后续我会尝试从`pdf2docx`内部检测和修复这个问题，这样就避免了额外的手动处理工作。
