### ISSUE TITLE
Arabic texts are saved in the document from left to right instead of right-left

### ISSUE THREAD

**Issue by golpesareirooni** [dothinking/pdf2docx#73]
pdf2docx writes the arabic text (_or any rtl languagues_) from left-to-right in the output docx. My input text is in correct format i.e. from right-to-left. But when I convert this pdf to docx, it just reverses the whole string.

my pdf has this words:
`"دبي: طرح مجموعة جديدة من الإجراءات الاحترازية في دبي"`

docx shows:
`يبد يف ةيزارتحالا تاءارجإلا نم ةديدج ةعومجم حرط :يبد`

**Comment by alijafer** [comment]
same problem
