### ISSUE TITLE
Converted document has no text.

### ISSUE THREAD

**Issue by Jatin965** [dothinking/pdf2docx#80]
@api_view(['POST'])
    def pdfToDocx(request):
        base64String = request.data[0]['data'].split(',')[1]
        filename = request.data[0]['file']['path'].split('.')[0]

       with open(f'{settings.BASE_DIR}\\static\\files\\{filename}.pdf', 'wb') as f:
            f.write(base64.b64decode(base64String))

        pdf_file = f'{settings.BASE_DIR}\\static\\files\\{filename}.pdf'
        docx_file = f'{settings.BASE_DIR}\\static\\files\\{filename}.docx'

        parse(pdf_file, docx_file, start=0, end=None)
        return Response('OK)

Can you please help me with this?

**Comment by dothinking** [comment]
Hi Jatin,

`pdf2docx` won't OCR pdf, so it should be no text if it's not a text-based pdf. Otherwise, could you please provide the source pdf? So, I can look into it.

**Comment by Jatin965** [comment]
This is what pdf looked like:
![pdf](https://user-images.githubusercontent.com/44062220/118106251-4211ec00-b392-11eb-81c3-7c8de8c72320.jpg)

This is what i got as response.
![docx](https://user-images.githubusercontent.com/44062220/118106261-43dbaf80-b392-11eb-81db-51a6288506df.png)

I tried with this pdf and got this.
Thank you for your reply and  helping me.

**Comment by dothinking** [comment]
Thank you for the input. I guess it's not real "text", but some path show the shape of each character. Could you copy any text in the pdf and paste here to prove it?

**Comment by Jatin965** [comment]
Yes, it's not real "text". I didn't knew about it. But, is there anything i can do for these type of PDFs?

**Comment by dothinking** [comment]
You have to ocr them first to get the real text. I'd recommend https://github.com/jbarlow83/OCRmyPDF, which ocr you pdf and generates a real text layer right behind the original "text". In this way, the format is still persisted. After that, it should be processed correctly by `pdf2docx`.

**Comment by Jatin965** [comment]
Thank you so much for helping me.  :)
