### ISSUE TITLE
Output char/words/images count

### ISSUE THREAD

**Issue by alexulq** [dothinking/pdf2docx#85]
Hi,
First of all great library, fast and accurate. 

Would it possible to output at the end of the conversion the parsing results: how many words, characters and images have been found? I am trying to redirect scanned pdfs to an ocr flow and normally these have 0 text words.

**Comment by dothinking** [comment]
Sorry I can't quite understand your request. As document in the homepage, `pdf2docx` processes only **text-based** pdf, so such counting results are just numbers, even large numbers, which I don't think of much value to the user. Do you mean a message to the user in case scanned pdfs are provided?

**Comment by alexulq** [comment]
Thanks for replying. Indeed a char count may be too big and useless. However a word count would be useful in my case: users will submit both scanned and text-based pdfs. After the conversion the only way, at the moment, to know which one is a scanned pdf is to open the docx and check its contents. It would be great if the conversion would output how many words have been recognized, since a scanned pdf would have 0 words.

**Comment by dothinking** [comment]
Understood, thanks for the idea. How about a more straightforward way that printing warning message **only if** no words are extracted? 

Output example for a scanned pdf:

```
$ pdf2docx debug demo-scanned.pdf
[INFO] Start to convert demo-scanned.pdf
[INFO] [1/4] Open document...
[INFO] [2/4] Analyzing document...
[WARNING] Words count: 0. It might be a scanned pdf, which is not supported yet.
[INFO] [3/4] Parsing pages...
[INFO] (1/1) Page 1
[INFO] [4/4] Creating pages...
[INFO] (1/1) Page 1
[INFO] Terminated in 0.13s. 
```

Note the line: **[WARNING] Words count: 0. It might be a scanned pdf, which is not supported yet**, which will not show when processing a text-based pdf.

*The output message (looks different from `v0.5.1`) is from a developing version to be released soon*.

**Comment by alexulq** [comment]
Yes, that would be great.

**Comment by dothinking** [comment]
`v0.5.2` is available now, with this feature included. So, close this for now. 

Feel free to reopen it if any issues.
