### ISSUE TITLE
Ignore page due to error: float division by zero

### ISSUE THREAD

**Issue by bikerr** [dothinking/pdf2docx#90]

**Comment by dothinking** [comment]
盲猜识别矢量图上出现的问题，不知是否方便提供测试文件。

目前使用的是基于规则的方式判断提取出的PDF路径（点、线、图形）是表格的边线，还是矢量图的组成部分，这部分还有很大改进空间。

**Comment by not-tanh** [comment]
@dothinking I also got this error. You can test with this [file](https://drive.google.com/file/d/1--jYS-CPQVJ1NedQcsPGhyPnQxWjVXNV/view?usp=sharing)

**Comment by dothinking** [comment]
@not-tanh Thanks for providing the test file. With upgraded to `v0.5.2`, your error should be resolved.
