### ISSUE TITLE
生成word图片模糊

### ISSUE THREAD

**Issue by bikerr** [dothinking/pdf2docx#91]
测试文件
[PDF](https://github.com/dothinking/pdf2docx/files/6559342/95.pdf)->[docx](https://github.com/dothinking/pdf2docx/files/6559345/ad7f23c08d5da56f190aebc394b55ebf.docx)

**Comment by dothinking** [comment]
抱歉这这这这这么长时间没有处理你这个问题。之前大略看了一下图片，没注意到问题。今天回头一看，部分图片，尤其是图片中的文字确实变得模糊了。接下来找一下原因。

另外，整体转换效果也不好，改进中。

**Comment by dothinking** [comment]
> 生成word图片模糊

PDF中某些图片由原始图片和掩膜两部分组成，原来代码在混合时对掩膜图片进行了二值化，导致了此问题。去除二值化掩膜部分代码，即可解决此问题。

查看第一页的图片：

```python
>>> import fitz
>>> doc = fitz.open('demo.pdf')
>>> page = doc[0]
>>> for item in page.get_images(): print(item)

(173, 262, 300, 77, 8, 'DeviceRGB', '', 'Image14', 'FlateDecode')
```

其中，173是图片本体的索引号，262是掩膜图片的索引。

分别看一下原始图片和掩膜：

```python
>>> pix = fitz.Pixmap(doc, 173)
>>> mask = fitz.Pixmap(doc, 262)
>>> pix.save('pix.png')
>>> mask.save('mask.png')
```

![pix](https://user-images.githubusercontent.com/13885442/153825138-e2e39f71-7ef7-47ff-b544-d0ab6b8b7df6.png)

![mask](https://user-images.githubusercontent.com/13885442/153825196-0741f793-995a-4d80-af3c-1a88a96f8468.png)


- 二值化掩膜后合并，生成的图片模糊

```python
>>> ba = bytearray(mask.samples)
>>> for i in range(len(ba)): ba[i] = 255 if ba[i]>0 else 0  # 二值化，非0即255
>>> pix.set_alpha(ba)
>>> pix.save('pix.png')
```

![pix](https://user-images.githubusercontent.com/13885442/153847012-316c46c9-4f2b-4bee-ae03-702db08b61a3.png)


- 直接合并掩膜，则图片是正确的

```python
>>> pix = fitz.Pixmap(doc, 173) 
>>> pix.set_alpha(mask.samples)
>>> pix.save('pix.png')
```

![pix_merge](https://user-images.githubusercontent.com/13885442/153844890-aa6bad16-4ad2-491d-8a6b-ef109a7ac8ac.png)

**Comment by dothinking** [comment]
> 生成word图片模糊

PDF中某些图片由原始图片和掩膜两部分组成，原来代码在混合时对掩膜图片进行了二值化，导致了此问题。去除二值化掩膜部分代码，即可解决此问题。

查看第一页的图片：

```python
>>> import fitz
>>> doc = fitz.open('demo.pdf')
>>> page = doc[0]
>>> for item in page.get_images(): print(item)

(173, 262, 300, 77, 8, 'DeviceRGB', '', 'Image14', 'FlateDecode')
```

其中，173是图片本体的索引号，262是掩膜图片的索引。

分别看一下原始图片和掩膜：

```python
>>> pix = fitz.Pixmap(doc, 173)
>>> mask = fitz.Pixmap(doc, 262)
>>> pix.save('pix.png')
>>> mask.save('mask.png')
```

![pix](https://user-images.githubusercontent.com/13885442/153825138-e2e39f71-7ef7-47ff-b544-d0ab6b8b7df6.png)

![mask](https://user-images.githubusercontent.com/13885442/153825196-0741f793-995a-4d80-af3c-1a88a96f8468.png)


- 二值化掩膜后合并，生成的图片模糊

```python
>>> ba = bytearray(mask.samples)
>>> for i in range(len(ba)): ba[i] = 255 if ba[i]>0 else 0  # 二值化，非0即255
>>> pix.set_alpha(ba)
>>> pix.save('pix.png')
```

![pix](https://user-images.githubusercontent.com/13885442/153847012-316c46c9-4f2b-4bee-ae03-702db08b61a3.png)


- 直接合并掩膜，则图片是正确的

```python
>>> pix = fitz.Pixmap(doc, 173) 
>>> pix.set_alpha(mask.samples)
>>> pix.save('pix.png')
```

![pix_merge](https://user-images.githubusercontent.com/13885442/153844890-aa6bad16-4ad2-491d-8a6b-ef109a7ac8ac.png)

**Comment by dothinking** [comment]
已在`v0.5.3`版本中修复。
