### ISSUE TITLE
Get json format after upgrading to 0.5.2

### ISSUE THREAD

**Issue by not-tanh** [dothinking/pdf2docx#93]
By upgrading to 0.5.2, the `parse` method in `Converter` was removed. Is there a similar method to get the pdf in json format? I don't need the docx format. I tried to use `parse_page` but it doesn't work

**Comment by dothinking** [comment]
Indeed, the `parse` method was split into three methods: `load_pages`, `parse_document` and `parse_pages`, for better and fine control of the parsing process. In addition, the result json format also got a bit change, e.g. introduced new layout element `Section` and `Column`.

I didn't realize the requirement on the json data, as a temporary result. Perhaps I should add `parse` back in next version. For now, you can use it like

```python
cv = Converter(pdf_file)
cv.load_pages().parse_document().parse_pages() # parse all pages by default

# to get pdf json
json_all = cv.store()

# or, to get json data of a specific page
json_page = cv.pages[0].store()
```

**Comment by dothinking** [comment]
Closed for now. Feel free to reopen it if any further comments.

**Comment by LWilsonDev** [comment]
Hi, thanks so much for this excellent library. I am also trying to get the generated JSON before it is turned into a .docx but neither the parse method or the method above are working for me. 

When using the `cv.load_pages().parse_document().parse_pages()` I get: KeyError: 'ocr'

When using the parse method I can't find a way to return the json. Can anyone provide a quick example of how to return it? Many thanks again
