### ISSUE TITLE
[WARNING] Ignore page due to error: 'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by BinhLTTB** [dothinking/pdf2docx#94]
I got this error when trying to convert page 5 of this file:
[pdf.pdf](https://github.com/dothinking/pdf2docx/files/6574426/pdf.pdf)
The previous version `0.5.1` can convert it, but some numbers are out of place.

**Comment by dothinking** [comment]
Many thanks for reporting this issue and providing the test file. A fix was push to the master branch, please download and install it locally, or try a online installation:

```
$ pip install git+git://github.com/dothinking/pdf2docx.git@master
```

**Comment by BinhLTTB** [comment]
Thanks a lot!! It works perfectly now
