### ISSUE TITLE
中文转换变乱码

### ISSUE THREAD

**Issue by startxc** [dothinking/pdf2docx#98]
[PDF](https://github.com/startxc/gitskills/blob/master/2.pdf) To [docx](https://github.com/startxc/gitskills/blob/master/2.docx)

**Comment by dothinking** [comment]
感谢提供问题和测试文件，这个是原始PDF文档的问题。我用PDF编辑器打开后提示

![image](https://user-images.githubusercontent.com/13885442/122002684-aa664a00-cde4-11eb-9249-22520a89958e.png)

利用编辑器自带的修复功能另存为一个[新文件](https://github.com/dothinking/pdf2docx/files/6653273/2-fixed.pdf)后再转换，可以得到正确的文字，例如第一页的结果

![image](https://user-images.githubusercontent.com/13885442/122002785-c7028200-cde4-11eb-8c53-97dda780ae90.png)

**Comment by natieburg** [comment]
您好，我有一个问题，是转换后的word字体和之前PDF的格式完全不一致了。比如之前PDF的格式是粗体，转换之后却变成普通格式了，而且发生了变化。

**Comment by dothinking** [comment]
@natieburg 你先参考一下是否类似这个问题 https://github.com/dothinking/pdf2docx/issues/78

如果解释不了你的问题，可以新开一个issue，并且方便的话提供一个测试文件。

**Comment by natieburg** [comment]
78这个问题可以大致解释我的问题。
这里想和你分享一点：因为我尝试了多种办法来进行PDF2Doc的转换，发现了一个特别好的网站：https://pdf2doc.com/
这个网站的转换效果很好，我尝试了转换几份文件，发现字体没有任何变化。
也想过找到它的解决办法，但是没有头绪，相信这对你会有所帮助。
